<ClockRect>:
    canvas:
        Color:
            rgba: 1, 0, 0, 1
        Rectangle:
            pos: self.pos
            size: (100, 100) # self.size

<AniRect>:
    canvas:
        Color:
            rgba: 0, 1, 0, 1
        Rectangle:
            pos: self.pos
            size: self.size

<AniLayout>:
    ani: ani
    AniRect:
        size: self.size
        pos: 200, 200
        id: ani
    ClockRect:
        size: self.size
        pos: 50, 50
